version: 2
jobs:
  build:
    working_directory: /go/src/github.com/confio/weave
    docker:
      - image: golang:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      GOPATH: /go

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Get tools
          command: make tools

      - run:
          name: Resolve dependencies
          command: make deps

      - run:
          name: Build
          command: make build

      - run:
          name: Run unit tests
          command: |
            make test | tee ${TEST_RESULTS}/go-test.out

      - run:
          name: Run coverage report
          command: make cover

      - run:
          name: Upload to codecov
          command: ./coverage/upload.sh

      - store_artifacts:
          path: ./coverage
          destination: coverage

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
